project:
  type: book
  post-render: 
    - quarto render --profile slides
    - bash docs.sh

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

comments:
  hypothesis: true

book:
  repo-url: "https://github.com/munch-group/analysis-template"
  repo-actions: [edit, issue, source]  
  title: "Title of your project"
  author: "Joanna Doh"  
  chapters:
    - index.qmd
    - workflow.py
    - part: "Notebooks"
      chapters: 
      - notebooks/template.ipynb
    - part: "Reports"
      chapters: 
      - reports/template.qmd
    - part: "Tables"
      chapters: 
      - tables/template.qmd
    - part: "Slides"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/template.qmd 
     
bibliography: references.bib
