{% set data = load_setup_py_data() %}

package:
  name: {{ data.get('name') }} 
  version: {{ data.get('version') }}  

source:
  git_url: https://github.com/munch-group/geneinfo.git

build:
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # entry_points:
  #   - exercises = exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:       # write here the list of libraries to look for your library dependencies
    - python
    - jupyter
    - ipython
    - matplotlib>=3.0
    - numpy>=1.1
    - requests
    - biopython
    - goatools>=1.2
    - pytables
    - wget

channels:    # write here the list of channels to look for your library dependencies
  # - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  
test:
  imports:
    - {{ data.get('name') }} 
  # commands:
  #   - exercises --help    

about:
  home: {{ data.get('url') }}
  license: MIT
  summary: {{ data.get('description') }}
  description: |
    {{ data.get('long_description') }}
